version: '3'

services:

  nginx:
    build:
      context: ./docker/dev
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - php
    volumes:
      - ./:/var/www/html/

  php:
    build:
      context: ./docker/dev
      dockerfile: php/Dockerfile
    container_name: php
    networks:
      - app-net
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app-net
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql-vol:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
    restart: always

networks:
  app-net:
    driver: bridge

volumes:
  mysql-vol:
    external: false
