# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $encryptionCollection: !tagged 'security.encryption'

    _instanceof:
        App\Request\FlashBagAwareInterface:
            calls:
                - ['setRequestStack', ['@request_stack']]
        App\Security\SecurityAwareInterface:
            calls:
                - ['setSecurity', ['@security.helper']]
        App\Security\Encryption\EncryptionInterface:
            tags: ['security.encryption']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # App > ArgumentValueResolver
    App\ArgumentValueResolver\FrameworkArgumentValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 150 }
    App\ArgumentValueResolver\InterviewArgumentValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 150 }

    # App > EventSubscriber
    App\EventSubscriber\EncryptionSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    # App > Loader
    App\Loader\SemverFileLoader:
        arguments: ['@file_locator']

    # App > Security
    App\Security\Encryption\Aes256Encryption:
        arguments:
            $passphrase: '%env(OPENSSL_AES256_PASSPHRASE)%'
            $cypher: '%env(OPENSSL_AES256_CYPHER)%'
